import os
from dotenv import load_dotenv

load_dotenv()

ELEVENLABS_API_KEY=os.getenv("ELEVENLABS_API_KEY")
HUGGINGFACEHUB_API_TOKEN=os.getenv("HUGGINGFACEHUB_API_TOKEN")
ELEVENLABS_VOICE_ID=os.getenv("ELEVENLABS_VOICE_ID")

RECORDING_SAMPLE_RATE=44100
RECORDING_CHANNELS=1
RECORDING_DURATION_SECONDS=10
TEMP_AUDIO_FILENAME="data/recordings/temp_user_response.wav"